export const dossierSource = {
  profile: {
    photo: '',
    firstName: 'Olena',
    lastName: 'Kravets',
    middleName: 'Mykhailivna',
    position: 'Judge of the Civil Chamber',
    department: 'Kyiv Court of Appeal',
    dossierId: 'JD-24-1187',
    registryCase: 'RC-2026-04-771',
    status: 'active',
  },
  personalInfo: {
    firstName: 'Olena',
    lastName: 'Kravets',
    middleName: 'Mykhailivna',
    birthDate: '1982-07-14',
    gender: 'female',
    taxId: '2894417621',
    citizenship: 'Ukraine',
  },
  address: {
    country: 'Ukraine',
    region: 'Kyiv Oblast',
    city: 'Kyiv',
    street: '11 Prorizna Street, Apt. 24',
    postalCode: '01001',
  },
  passport: {
    series: 'MK',
    number: '483921',
    issuedBy: 'State Migration Service of Ukraine, Kyiv Unit',
    issueDate: '2017-05-12',
    expiryDate: '2027-05-12',
  },
  contacts: {
    phone: '+380 67 555 41 22',
    email: 'o.kravets@judiciary.gov.ua',
    emergencyContact: 'Roman Kravets, +380 50 908 11 38',
  },
  education: {
    degree: 'Master of Laws',
    institution: 'Taras Shevchenko National University of Kyiv',
    specialization: 'Judicial administration and civil procedure',
    graduationYear: '2004',
    studyForm: 'fullTime',
  },
  registryHistory: [
    {
      id: 'rh-1',
      recordDate: '2026-02-18',
      registry: 'Judicial Appointments Registry',
      action: 'Annual qualification review updated',
      reference: 'Order QA-18/2026',
      operator: 'High Qualification Commission',
    },
    {
      id: 'rh-2',
      recordDate: '2025-11-03',
      registry: 'Asset Declaration Registry',
      action: 'Declaration addendum attached',
      reference: 'Declaration 4A-9931',
      operator: 'National Agency on Corruption Prevention',
    },
    {
      id: 'rh-3',
      recordDate: '2025-06-26',
      registry: 'Disciplinary Proceedings Registry',
      action: 'Closed proceeding archived',
      reference: 'File DP-07-221',
      operator: 'Judicial Governance Inspectorate',
    },
  ],
  riskAnalysis: {
    score: 62,
    level: 'high',
    lastReview: '2026-03-14',
    flags: ['assetMismatch', 'mediaExposure', 'disciplinary'],
  },
}
